### ISSUE TITLE
Safe creation on Rinkeby with Compound test DAI fails

### ISSUE THREAD

**Issue by rmeissner** [gnosis/safe-relay-service#149]
Safe creation on Rinkeby with the compound test DAI (`0x5592EC0cfb4dbc12D3aB100b257153436a1f0FEa`) fails and results in an endless retry for the creation every couple seconds that throws again.

```
Safe relay service threw an error (pod: rinkeby-safe-relay-worker): 
2019-09-03 08:30:39,625 [ERROR] [ForkPoolWorker-1] Task safe_relay_service.relay.tasks.deploy_create2_safe_task[0576b4c4-46ca-4dab-9dca-f10fec682ede] raised unexpected: BadFunctionCallOutput("Could not decode contract function call createProxyWithNonce return data b'' for output_types ['address']")
Traceback (most recent call last):
 File "/usr/local/lib/python3.7/site-packages/web3/contract.py", line 1372, in call_contract_function
   output_data = decode_abi(output_types, return_data)
 File "/usr/local/lib/python3.7/site-packages/eth_abi/abi.py", line 96, in decode_abi
   return decoder(stream)
 File "/usr/local/lib/python3.7/site-packages/eth_abi/decoding.py", line 118, in __call__
   return self.decode(stream)
 File "/usr/local/lib/python3.7/site-packages/eth_utils/functional.py", line 45, in inner
   return callback(fn(*args, **kwargs))
 File "/usr/local/lib/python3.7/site-packages/eth_abi/decoding.py", line 164, in decode
   yield decoder(stream)
 File "/usr/local/lib/python3.7/site-packages/eth_abi/decoding.py", line 118, in __call__
   return self.decode(stream)
 File "/usr/local/lib/python3.7/site-packages/eth_abi/decoding.py", line 186, in decode
   raw_data = self.read_data_from_stream(stream)
 File "/usr/local/lib/python3.7/site-packages/eth_abi/decoding.py", line 296, in read_data_from_stream
   len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
 File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
   R = retval = fun(*args, **kwargs)
 File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
   return self.run(*args, **kwargs)
 File "/app/safe_relay_service/relay/tasks.py", line 264, in deploy_create2_safe_task
   SafeCreationServiceProvider().deploy_create2_safe_tx(safe_address)
 File "/app/safe_relay_service/relay/services/safe_creation_service.py", line 261, in deploy_create2_safe_tx
   nonce=tx_nonce)
 File "/usr/local/lib/python3.7/site-packages/gnosis/safe/proxy_factory.py", line 108, in deploy_proxy_contract_with_nonce
   contract_address = create_proxy_fn.call()
 File "/usr/local/lib/python3.7/site-packages/web3/contract.py", line 1115, in call
   **self.kwargs
 File "/usr/local/lib/python3.7/site-packages/web3/contract.py", line 1394, in call_contract_function
   raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call createProxyWithNonce return data b'' for output_types ['address']
```

**Comment by Uxio0** [comment]
@rmeissner I'm checking compound implementation of ERC20, it's not standard. I guess we are having the problem when doing the refund:

https://etherscan.io/address/0xF5DCe57282A584D2746FaF1593d3121Fcac444dC
https://github.com/gnosis/safe-contracts/blob/development/contracts/common/SecuredTokenTransfer.sol

```
    ///
    /// !!!!!!!!!!!!!!
    /// !!! NOTICE !!! `transfer` does not return a value, in violation of the ERC-20 specification
    /// !!!!!!!!!!!!!!
    ///

    /**
      * @notice Transfer `amount` tokens from `msg.sender` to `dst`
      * @param dst The address of the destination account
      * @param amount The number of tokens to transfer
      */
    function transfer(address dst, uint256 amount) external;
```

**Comment by rmeissner** [comment]
The contracts support this (i also used it as a payment token for transactions, it just fails for creation)

**Comment by Uxio0** [comment]
Good to know, thanks
