### ISSUE TITLE
Error during Admin UI Add token

### ISSUE THREAD

**Issue by amaurer** [gnosis/safe-relay-service#263]
**Describe the bug**
When using the web admin UI and attempting to add a token, a 500 error response is returned from the web app.  I didn't see in the documentation any other way to add a token to the relayer.

**To Reproduce**
1. Install Docker-compose production environment
2. Setup admin account via docker exec scripts
3. Login to Admin UI
4. click on "token Add+"
5. Witness 500 error

**Expected behavior**
I would expect to see form fields with attributes to populate regarding tokens

**Additional context**
Running against Infura Kovan endpoint. 
Docker images. Did recent `docker-compose pull`
![image](https://user-images.githubusercontent.com/561465/97187455-d317d180-1778-11eb-9213-e12da3b1390a.png)

Error Logs from worker...

```
2020-10-26 14:43:21,391 [ERROR] [MainProcess] Internal Server Error: /admin/tokens/token/add/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/options.py", line 575, in get_field
    return self.fields_map[field_name]
KeyError: 'eth_value'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 264, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/utils.py", line 295, in _get_non_gfk_field
    field = opts.get_field(name)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/options.py", line 577, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Token has no field named 'eth_value'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 202, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
```

**Comment by Uxio0** [comment]
Thanks for the report, it's fixed now
